// <auto-generated />
using System;
using AprendeLibre.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AprendeLibre.Migrations
{
    [DbContext(typeof(AplDbContext))]
    partial class AplDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AprendeLibre.Models.BlockNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__BlockNot__3213E83FF58F31BD");

                    b.ToTable("BlockNotas");
                });

            modelBuilder.Entity("AprendeLibre.Models.Categorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3213E83F9B8F8547");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("AprendeLibre.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdGrados")
                        .HasColumnType("int")
                        .HasColumnName("Id_Grados");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubirArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Clases__3213E83F8A275EE4");

                    b.HasIndex("IdGrados");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("AprendeLibre.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Comentario");

                    b.Property<int>("IdGrados")
                        .HasColumnType("int")
                        .HasColumnName("Id_Grados");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.HasKey("Id")
                        .HasName("PK__Comentar__3213E83F7FBEC386");

                    b.HasIndex("IdGrados");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("AprendeLibre.Models.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreGrado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Grados__3213E83FE53D0E1A");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("AprendeLibre.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("Id_Categoria");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreLibro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Libros__3213E83FFE70F228");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("AprendeLibre.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Materias__3213E83FDAAE9F50");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("AprendeLibre.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Recursos__3213E83FDBB09EF1");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("AprendeLibre.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3213E83F05CF4266");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AprendeLibre.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Usuario_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("Rol_Id");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__771110D532B95B4A");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GradosMateria", b =>
                {
                    b.Property<int>("GradosId")
                        .HasColumnType("int")
                        .HasColumnName("Grados_Id");

                    b.Property<int>("MateriasId")
                        .HasColumnType("int")
                        .HasColumnName("Materias_id");

                    b.HasKey("GradosId", "MateriasId")
                        .HasName("PK__Grados_M__B36A28B88FD67482");

                    b.HasIndex("MateriasId");

                    b.ToTable("Grados_Materias", (string)null);
                });

            modelBuilder.Entity("LibrosCategorium", b =>
                {
                    b.Property<int>("LibrosId")
                        .HasColumnType("int")
                        .HasColumnName("Libros_Id");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("Categoria_id");

                    b.HasKey("LibrosId", "CategoriaId")
                        .HasName("PK__Libros_C__90CE5D48205B2977");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Libros_Categoria", (string)null);
                });

            modelBuilder.Entity("AprendeLibre.Models.Clase", b =>
                {
                    b.HasOne("AprendeLibre.Models.Grado", "IdGradosNavigation")
                        .WithMany("Clases")
                        .HasForeignKey("IdGrados")
                        .IsRequired()
                        .HasConstraintName("FK_Clases_Grados");

                    b.Navigation("IdGradosNavigation");
                });

            modelBuilder.Entity("AprendeLibre.Models.Comentario", b =>
                {
                    b.HasOne("AprendeLibre.Models.Grado", "IdGradosNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdGrados")
                        .IsRequired()
                        .HasConstraintName("FK_Comentarios_Grados");

                    b.HasOne("AprendeLibre.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Comentarios_Usuarios");

                    b.Navigation("IdGradosNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AprendeLibre.Models.Libro", b =>
                {
                    b.HasOne("AprendeLibre.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Libros_Categoria");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("AprendeLibre.Models.Usuario", b =>
                {
                    b.HasOne("AprendeLibre.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GradosMateria", b =>
                {
                    b.HasOne("AprendeLibre.Models.Grado", null)
                        .WithMany()
                        .HasForeignKey("GradosId")
                        .IsRequired()
                        .HasConstraintName("FK_Grados_Materias_Grados");

                    b.HasOne("AprendeLibre.Models.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriasId")
                        .IsRequired()
                        .HasConstraintName("FK_Grados_Materias_Materias");
                });

            modelBuilder.Entity("LibrosCategorium", b =>
                {
                    b.HasOne("AprendeLibre.Models.Categorium", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Libros_Categoria_Categoria");

                    b.HasOne("AprendeLibre.Models.Libro", null)
                        .WithMany()
                        .HasForeignKey("LibrosId")
                        .IsRequired()
                        .HasConstraintName("FK_Libros_Categoria_Libros");
                });

            modelBuilder.Entity("AprendeLibre.Models.Categorium", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("AprendeLibre.Models.Grado", b =>
                {
                    b.Navigation("Clases");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("AprendeLibre.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AprendeLibre.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
